name: "CLA Assistant Lite"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  cla-assistant-lite:
    uses: morisawa-inc/cla-assistant-lite-reusable-workflow/.github/workflows/cla.yml@main
    secrets:
      personal-access-token: ${{ secrets.CLA_ASSISTANT_GITHUB_TOKEN }}
